### ISSUE TITLE
Feature - Provide more storage types for persistent volume storage

### ISSUE THREAD

**Issue by hoksanyip** [abnamro/repository-scanner#235]
**Is your feature request related to a problem? Please describe.**

Currently, there are two options to set the storage engine of persistent volume: using parameters `local` and `hostPath`, which in both cases will store the data locally in the nodes themselves. As we are trying to set this up the cloud using server-less containers, this would not be viable. Instead, using [CSI](https://kubernetes.io/docs/concepts/storage/volumes/#csi)-backed storages would be would be nice to have. And given the reasonable standardised interface (for most of the drivers, it works by adding parameters in `csi` specs key, it can be made quite generic for most, if not all, types of CSI drivers.

**Describe the solution you'd like**

As an alternative to providing the `hostOS` in the helm values, add an option to add parameters to `csi`, for example, instead of the values (for example in https://github.com/abnamro/repository-scanner/blob/main/deployment/kubernetes/charts/resc-database/values.yaml):

```yaml
hostOS: "windows"
database:
   pvc_path: "/var/resc/mssql/data"
  pvc_size: 10Gi
```
add an option to specify to store the persistent volumes in AWS EFS CSI:

```yaml
database:
  ...
  storageType: "csi" 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [[fs-id]]::[[fsap-id]]
```
so it can directly be inserted as-is in PersistentVolume resource.

**Describe alternatives you've considered**

**Additional context**
