### ISSUE TITLE
Feature - Allow option to provide additional annotations in services

### ISSUE THREAD

**Issue by hoksanyip** [abnamro/repository-scanner#238]
**Is your feature request related to a problem? Please describe.**
I am trying to configure the application in combination with AWS Load balancer Controller to configure the access outside of the cluster. For this, I need to add additional annotations in the services to make it work, but there is currently no option yet to provide it through Helm custom values.

**Describe the solution you'd like**
Provide a way for user-defined annotations to be added to the services (frontend and api), something like:

```yaml
apiVersion: v1
kind: Service
metadata:
  ...
  annotations:
     {{ if .Values.service.annotaions }}
     {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  ...
```
for both `charts/resc-frontend/templates/frontend_service.yaml` as well as `templates/web_service_service.tpl`

**Describe alternatives you've considered**
Alternatively, having the same path used for health checks (for example `/heath` on root level) would also work, but it would be nice to have a the same base URL used for both services.

**Additional context**
